### PR TITLE
Feature/requirements

### PR DESCRIPTION
**Pull request by FeGeyer**
Added a `requirements.txt`, which contains all required packages for this project. This file is used in the `setup.py` .

To test: make a new virtual environment and install everything you need with `pip install -e .`

### CODE REVIEW

**Comment by beckstev** [comment]
How did you created `requirements.txt`?

**Comment by beckstev** [comment]
Did you try to reinstall the package with the new `setup.py`? As you know, I am currently not using a virtual enviroment and do not want to risk to destroy all of my dependencies.

**Comment by FeGeyer** [comment]
> How did you created requirements.txt?

With `pip freeze > <name of the txt file>`. This [link](https://medium.com/python-pandemonium/better-python-dependency-and-package-management-b5d8ea29dff1) says it works for virtual environments, i dont know if it works outside too.

**Comment by FeGeyer** [comment]
> Did you try to reinstall the package with the new setup.py? As you know, I am currently not using a virtual enviroment and do not want to risk to destroy all of my dependencies.

I created multiple new virtual environments and executed `pip install -e .`. After this i could execute the `training.py` and the `train_autoencoder.py` like always.

**Pull request merged**
